### ISSUE TITLE
[hardknott] cargo.bbclass needs to be cargo_bin.bbclass

### ISSUE THREAD

**Issue by moto-timo** [UpdateHub/meta-updatehub#101]
meta-rust-bin (master branch) is the only place where "hardknott" is supported and the cargo.bbclass is now cargo_bin.bbclass.

Also, meta-qt5 should be in LAYERRECOMMENDS so that layerindex can parse the dynamic-layers recipes which inherit qt5 bbclasses.

https://layers.openembedded.org/layerindex/updates/39192/

**Comment by rafluan** [comment]
This was fixed here: 

`https://github.com/UpdateHub/meta-updatehub/commit/5d15d658d5769609338bcf0b7ecb054b1b0a5e76`
